config/routes.rb
Rails.application.routes.draw do

  root 'marketing#index'
  devise_for :dealers
  namespace 'dealer' do
    resources :dealerships do
      resources :models, path: 'cars' do
        resources :images
      end
      collection do
        get 'carslist', to: 'models#cars_list'
      end
    end
  end

  namespace 'api', defaults: { format: :json} do
    namespace 'v1' do
      resources :dealerships, only: [:index, :show] do
        resources :models, only: [:index, :show]
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(dealer)
    if dealer.dealership_admins.any?
      can [:create, :new], [Dealership, Model, ]
      can :manage, Dealership, admin_id: dealer.id
      can :manage, Model, dealership: { id: dealer.dealership_admin_ids }
      can :manage, Picture do |picture|
        Model.joins(:dealership).where(dealerships: { admin_id: a.id }).pluck(:id).include?(picture.imageable_id) && picture.imageable_type.eql?("Model")
      end
    else
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/body_style.rb
class BodyStyle < ApplicationRecord
  validates :name, presence: true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :make
end

app/models/dealer.rb
class Dealer < ApplicationRecord
  has_and_belongs_to_many :dealerships
  has_many :dealership_admins, class_name: "Dealership",
            foreign_key: :admin_id, dependent: :nullify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/dealership.rb
class Dealership < ApplicationRecord
  #associations
  has_and_belongs_to_many :dealers
  belongs_to :admin, class_name: "Dealer", foreign_key: :admin_id
  has_many :models
  #validations
  validates :name, presence: true
end

app/models/make.rb
class Make < ApplicationRecord
  has_many :cars
end

app/models/model.rb
class Model < ApplicationRecord
  belongs_to :car
  belongs_to :dealership
  has_many :pictures, as: :imageable

  validates :price, presence: true, numericality: { only_integer: true }
  validates :year, presence: true, numericality: { only_integer: true }


  def master_picture
    if pictures.any?
      return "https://cartruckdealerships.herokuapp.com" + pictures.first.image_url
    end
    "https://lorempixel.com/400/300/transport/3/"
  end
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :imageable, polymorphic: true

  validates :image, presence: true
  mount_uploader :image, CarpicUploader
end

app/controllers/api/v1/dealerships_controller.rb
class Api::V1::DealershipsController < ApplicationController

  def index
    @dealerships = Dealership.all
    render json: @dealerships
  end

  def show
    @dealership = Dealership.find(params[:id])
  end
end

app/controllers/api/v1/models_controller.rb
class Api::V1::ModelsController < ApplicationController
  def index
    sleep 3
    @dealership = Dealership.find(params[:dealership_id])
    @models = @dealership.models
  end

  def show
    @dealership = Dealership.find(params[:dealership_id])
    @model = @dealership.models.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
   dealer_dealerships_path
  end

  def current_ability
    @current_ability ||= ::Ability.new(current_dealer)
  end
end

app/controllers/dealer/dealerships_controller.rb
class Dealer::DealershipsController < ApplicationController
  before_action :authenticate_dealer!
  load_and_authorize_resource

  def index
    @dealership_admins = current_dealer.dealerships.where(admin: current_dealer)
    @dealerships = current_dealer.dealerships.where.not(admin: current_dealer)
  end

  def show
    @dealership = Dealership.find(params[:id])
    @models = @dealership.models
  end
end

app/controllers/dealer/images_controller.rb
class Dealer::ImagesController < ApplicationController
  before_action :authenticate_dealer!

  def index
    @dealership = Dealership.find(params[:dealership_id])
    @model = Model.find(params[:model_id])
    @images = @model.pictures
    authorize! :show, @dealership
    authorize! :show, @model
  end

  def new
    @dealership = Dealership.find(params[:dealership_id])
    @model = Model.find(params[:model_id])
    authorize! :show, @dealership
    authorize! :show, @model
    @picture = @model.pictures.build
  end


  def create
    @dealership = Dealership.find(params[:dealership_id])
    @model = Model.find(params[:model_id])
    authorize! :show, @dealership
    authorize! :show, @model
    @picture = Picture.new(picture_params)
    @picture.imageable_id = @model.id
    @picture.imageable_type = "Model"
    if @picture.save
      flash[:success] = "Image added"
      redirect_to dealer_dealership_model_images_path
    else
      render 'new'
    end
  end

  private

  def picture_params
    params.require(:picture).permit(:image)
  end
end

app/controllers/dealer/models_controller.rb
class Dealer::ModelsController < ApplicationController
  before_action :authenticate_dealer!
  load_and_authorize_resource except: :cars_list

  def new
    @model = Model.new
  end

  def create
    @model = Model.new(model_params)
    @dealership = Dealership.find(params[:dealership_id])
    if current_dealer.dealership_ids.include?(params[:dealership_id].to_i)
      dealership = Dealership.find(params[:dealership_id])
      @model.dealership_id =  dealership.id
    end
    if @model.save
      flash[:success] = "Car created"
      redirect_to dealer_dealership_model_path(@dealership, @model)
    else
      render 'new'
    end
  end

  def show
    @dealership = Dealership.find(params[:dealership_id])
    @model = Model.find(params[:id])
  end

  def cars_list
    make = Make.find(params[:id])
    render json: make.cars
  end

  private

  def model_params
    params.require(:model).permit(:car_id, :year, :price)
  end
end

app/controllers/marketing_controller.rb
class MarketingController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carpic_helper.rb
module CarpicHelper
end

app/views/dealer/dealerships/index.html.erb
<h1>Dealerships</h1>

<% if @dealership_admins.size > 0 %>
  <h2>Admin</h2>
  <table>
    <% @dealership_admins.each do |dealership| %>
      <tr>
        <td><%= link_to dealership.name, dealer_dealership_path(dealership) %></td>
      </tr>
    <% end %>
  </table>
<% end %>
<% if @dealerships.size > 0 %>
  <h2>Dealerships</h2>
  <table>
    <% @dealerships.each do |dealership| %>
      <tr>
        <td><%= link_to dealership.name, dealer_dealership_path(dealership) %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/dealer/dealerships/show.html.erb
<h1><%= @dealership.name %></h1>
<div class="row">
  <!-- Dealer Info -->
</div>
<div class="row">
  <div class="col-md-10">
    <h2>Cars</h2>
    <table class='table'>
      <% @models.each do |model| %>
        <tr>
          <td><%= model.car.model %></td>
          <td><%= model.year %></td>
          <td><%= number_to_currency(model.price, currency: '$') %></td>
          <td><%= link_to "Edit", dealer_dealership_model_path(model) %></td>
        </tr>
      <% end %>
    </table>
  </div>
  <div class="col">
    <ul class="nav flex-column">
      <li class="nav-item">
        <%= link_to 'New Car', new_dealer_dealership_model_path(@dealership) %>
      </li>
    </ul>
  </div>
</div>

app/views/dealer/images/index.html.erb
<h1>Images</h1>
<div class="row">
  <div class="col-md-10">
    <table class='table'>
      <% @images.each do |image| %>
        <tr>
          <td><%= image.id %></td>
          <td><%= image_tag image.image.url(:thumb) %></td>
        </tr>
      <% end %>
    </table>
  </div>
  <div class="col">
    <ul class="nav flex-column">
      <li class="nav-item">
        <%= link_to "Car Details", dealer_dealership_model_path(@dealership, @model), class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Add Image", new_dealer_dealership_model_image_path(@dealership, @model), class: 'nav-link' %>
      </li>
    </ul>
  </div>
</div>

app/views/dealer/images/new.html.erb
<h1>New Carpicture</h1>

<div class="row">
  <div class="col-md-10">
    <%= form_for @picture, url: dealer_dealership_model_images_path(@dealership, @model) do |f| %>
      <% if @picture.errors.any? %>
        <h3>Errors</h3>
        <ul>
          <% @picture.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.file_field :image %>
      </div>

      <%= f.submit "Add image", class: 'btn btn-primary' %>
    <% end %>
  </div>
  <div class="col">
    <div class="col">
      <ul class="nav flex-column">
        <li class="nav-item">
          <%= link_to "Car Details", dealer_dealership_model_path(dealership_id: @dealership.id, id: @model.id), class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Images", dealer_dealership_model_images_path(dealership_id: @dealership.id, model_id: @model.id), class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/dealer/models/new.html.erb
<h1>New Car</h1>

<%= form_for @model, url: dealer_dealership_models_path do |f| %>
  <% if @model.errors.any? %>
    <h3>Errors</h3>
    <ul>
      <% @model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="form-group">
    <label for="make">Make</label>
    <%= select_tag :make, options_from_collection_for_select(Make.order('code'), 'id', 'name'), include_blank: true, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :car %>
    <%= f.select :car_id, {}, {include_blank: true}, { class: 'form-control' }%>
  </div>
  <div class="form-group">
    <%= f.label :year %>
    <%= f.text_field :year, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: 'form-control' %>
  </div>
  <%= f.submit "Create car", class: 'btn btn-primary' %>
<% end %>

<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script type="text/javascript">
  $('#make').change(function(){
    axios.get('/dealer/dealerships/carslist?id=' + $('#make').val())
      .then(function(response){
        $('#model_car_id').html('')
        $.each(response.data, function(i, data){
          $('#model_car_id').append(
            "<option value='" + data.id + "''>" + data.model + "</option>"
          )
        })
      })
  })
</script>

app/views/dealer/models/show.html.erb
<h1><%=@model.car.make.name %> <%= @model.car.model %></h1>
<div class="row">
  <div class="col col-md-10">
    <table class='table'>
      <tr>
        <td><b>Year </b></td>
        <td><%= @model.year %></td>
      </tr>
      <tr>
        <td><b>Price </b></td>
        <td><%= number_to_currency(@model.price, currency: '$') %></td>
      </tr>
    </table>
  </div>
  <div class="col">
    <ul class="nav flex-column">
      <li class="nav-item">
        <%= link_to "All Cars", dealer_dealership_path(@dealership), class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Images", dealer_dealership_model_images_path(dealership_id: @dealership.id, model_id: @model.id), class: 'nav-link' %>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse bg-primary">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="/">CTD</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if dealer_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Dealer panel", dealer_dealerships_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
    <ul class="navbar-nav mr-right">
      <% if dealer_signed_in? %>
        <li class="nav-item">
          <%= link_to "Logout", destroy_dealer_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign in", new_dealer_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", new_dealer_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CarTruckDelaerships</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
    <!-- jQuery first, then Tether, then Bootstrap JS. -->

    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  </body>
</html>

app/views/marketing/about.html.erb
<h1>Marketing#about</h1>
<p>Find me in app/views/marketing/about.html.erb</p>

app/views/marketing/contact.html.erb
<h1>Marketing#contact</h1>
<p>Find me in app/views/marketing/contact.html.erb</p>

app/views/marketing/index.html.erb
<div class="jumbotron">
  <h1 class="display-3">Car Truck Dealership</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
  </p>
</div>